name: betty_resource
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/
    - assets/bettygeneral/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/quicksand/Quicksand-Regular.ttf
        - asset: fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
