name: betty_resource
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  get: ^4.6.6
  intl: ^0.20.1
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/icon/
    - assets/image/
    - assets/lottie/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/quicksand/Quicksand-Regular.ttf
        - asset: fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: fonts/satoshi/Satoshi-Light.otf
          weight: 300
        - asset: fonts/satoshi/Satoshi-Regular.otf
        - asset: fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: fonts/satoshi/Satoshi-Medium.otf
          weight: 600
        - asset: fonts/satoshi/Satoshi-Bold.otf
          weight: 700
        - asset: fonts/satoshi/Satoshi-Black.otf
          weight: 700
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: fonts/inter/Inter-VariableFont_opsz,wght.ttf
    - family: SF-Pro
      fonts:
        - asset: fonts/sf-pro/SF-Pro-Thin.otf
          weight: 100
        - asset: fonts/sf-pro/SF-Pro-ThinItalic.otf
          weight: 100
          style: italic
        - asset: fonts/sf-pro/SF-Pro-Extralight.otf
          weight: 200
        - asset: fonts/sf-pro/SF-Pro-ExtralightItalic.otf
          weight: 200
          style: italic
        - asset: fonts/sf-pro/SF-Pro-Light.otf
          weight: 300
        - asset: fonts/sf-pro/SF-Pro-LightItalic.otf
          weight: 300
          style: italic
        - asset: fonts/sf-pro/SF-Pro-Regular.otf
          weight: 400
        - asset: fonts/sf-pro/SF-Pro-RegularItalic.otf
          weight: 400
          style: italic
        - asset: fonts/sf-pro/SF-Pro-Medium.otf
          weight: 500
        - asset: fonts/sf-pro/SF-Pro-MediumItalic.otf
          weight: 500
          style: italic
        - asset: fonts/sf-pro/SF-Pro-Semibold.otf
          weight: 600
        - asset: fonts/sf-pro/SF-Pro-SemiboldItalic.otf
          weight: 600
          style: italic
        - asset: fonts/sf-pro/SF-Pro-Bold.otf
          weight: 700
        - asset: fonts/sf-pro/SF-Pro-BoldItalic.otf
          weight: 700
          style: italic
        - asset: fonts/sf-pro/SF-Pro-Heavy.otf
          weight: 800
        - asset: fonts/sf-pro/SF-Pro-HeavyItalic.otf
          weight: 800
          style: italic
        - asset: fonts/sf-pro/SF-Pro-Black.otf
          weight: 900
        - asset: fonts/sf-pro/SF-Pro-BlackItalic.otf
          weight: 900
          style: italic
