name: betty_resource
description: "A new Flutter package project."
version: 0.0.1
homepage: null

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  get: ^4.6.6

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/icon/
    - assets/image/
    - assets/lottie/

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/quicksand/Quicksand-Light.ttf
          weight: 300
        - asset: fonts/quicksand/Quicksand-Regular.ttf
        - asset: fonts/quicksand/Quicksand-Medium.ttf
          weight: 500
        - asset: fonts/quicksand/Quicksand-SemiBold.ttf
          weight: 600
        - asset: fonts/quicksand/Quicksand-Bold.ttf
          weight: 700
    - family: Satoshi
      fonts:
        - asset: fonts/satoshi/Satoshi-Light.otf
          weight: 300
        - asset: fonts/satoshi/Satoshi-Regular.otf
        - asset: fonts/satoshi/Satoshi-Medium.otf
          weight: 500
        - asset: fonts/satoshi/Satoshi-Medium.otf
          weight: 600
        - asset: fonts/satoshi/Satoshi-Bold.otf
          weight: 700
        - asset: fonts/satoshi/Satoshi-Black.otf
          weight: 700
    - family: Inter
      fonts:
        - asset: fonts/inter/Inter-Italic-VariableFont_opsz,wght.ttf
        - asset: fonts/inter/Inter-VariableFont_opsz,wght.ttf
    - family: SF-Pro
      fonts:
        - asset: fonts/sf-pro/SFPRODISPLAYBLACKITALIC.OTF
        - asset: fonts/sf-pro/SFPRODISPLAYBOLD.OTF
        - asset: fonts/sf-pro/SFPRODISPLAYHEAVYITALIC.OTF
        - asset: fonts/sf-pro/SFPRODISPLAYLIGHTITALIC.OTF
        - asset: fonts/sf-pro/SFPRODISPLAYMEDIUM.OTF
        - asset: fonts/sf-pro/SFPRODISPLAYREGULAR.OTF
        - asset: fonts/sf-pro/SFPRODISPLAYSEMIBOLDITALIC.OTF
        - asset: fonts/sf-pro/SFPRODISPLAYTHINITALIC.OTF
        - asset: fonts/sf-pro/SFPRODISPLAYULTRALIGHTITALIC.OTF
